### ISSUE TITLE
gold passages data for all languages

### ISSUE THREAD

**Issue by edchengg** [masakhane-io/afriqa#22]
Hi,
Thanks for releasing the data.
it seems there are 5 languages in https://github.com/masakhane-io/afriqa/tree/main/data/gold_passages
and in Table 7 there are 10 langs.
Would it be possible to release the rest languages?
Thank you.

**Comment by ToluClassics** [comment]
Hi @edchengg , thanks for your interest in Afriqa!, working on releasing gold passages for all languages. Should be available in a day or two
